# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml TEST

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    yarn install --frozen-lockfile --no-progress --non-interactive --network-concurrency 1
    yarn build
  displayName: 'Compile (install modules and build)'

- script: |
    yarn test:coverage
    "bash <(curl -s https://codecov.io/bash)" 
  displayName: 'tests'

- script: |
    yarn lint
  displayName: 'lint'

- script: |
    npm install oval
    npx oval validate -p openapi/index.yaml
  displayName: 'lint-api'

  
