# Azure DevOps pipeline to build, run tests, and more.

pool:
  vmImage: 'ubuntu-latest'

jobs:
  # 1) Install Node.js modules and build
  - job: compile
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.14.1'
      displayName: 'Install Node.js'
    
    # TODO: restore_node_cache
    - script: |
        echo 'restore_node_cache'
      displayName: 'Restore node cache'

    - script: |
        yarn install --frozen-lockfile --no-progress --non-interactive --network-concurrency 1
      displayName: 'Install node modules'

    # TODO: save_node_cache
    - script: |
        echo 'save_node_cache'
      displayName: 'Save node cache'

    - script: |
        yarn build
      displayName: 'Build'

  # 2.A) Run unit tests
  - job: tests
    dependsOn: compile
    steps:
    - script: |
        yarn test:coverage
      displayName: 'Unit tests'

    # TODO: "bash <(curl -s https://codecov.io/bash)"
    - bash: |
        echo 'codecov'
      displayName: 'Code coverage'
 
  # 2.B) Analyze source code
  - job: lint
    dependsOn: compile
    steps:
    - script: |
        yarn lint
      displayName: 'Lint'

  # 2.C) Validate OpenAPI spec 
  - job: lint_api
    dependsOn: compile
    steps:
    - script: |
        npm install oval
      displayName: 'Install OpenAPI validator'

    - script: |
        npx oval validate -p openapi/index.yaml
      displayName: 'OpenAPI validator'

